training: !!bool "true"
device: "cuda"
unprocessed_data: '/Users/bapt/Desktop/ENSAE/3ème Année/Advanced Machine Learning/LibriSpeech/train-clean-360/*/*'
---
data:
    train_path: '/Users/bapt/Desktop/ENSAE/3ème Année/Advanced Machine Learning/datasets/train'
    test_path: '/Users/bapt/Desktop/ENSAE/3ème Année/Advanced Machine Learning/datasets/test'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 160 #Number of frames as input for the log-mel-spectrogram
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: './model.model' #Model path for testing, inference, or resuming training
---
train:
    N : 64 #Number of speakers in batch
    M : 10 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    ratio: 0.9 #Ratio of train speakers
    lr: 0.01 
    epochs: 950 #Max training speaker epoch 
    log_interval: 30 #Epochs before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 64 #Number of speakers in batch
    M : 10 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs